spring:
  application:
    name: user-microservice # Updated application name for user-microservice
  cloud:
    config:
      uri: http://localhost:8888 # Address of your Config Server
      import: "optional:configserver:" # Correct use of optional import to avoid errors
      import-check:
        enabled: false # Disable config import validation to prevent errors

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka Server address

management:
  tracing:
    sampling:
      probability: 1.0 # Sampling rate for tracing (1.0 means all requests will be traced)